name: Hexo build and deploy

on:
  push:
    branches:
      - blog # blog分支是主代码分支，master分支是打包后代码存放分支（供GitHub Pages使用）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          # checkout到你的hexo代码分支
          ref: blog
          # hexo需要加载内部子模块
          submodules: true
          # 下载 git submodule
      # - name: update theme from submodule
      #   uses: srt32/git-actions@v0.0.3
      #   with:
      #     args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      # 安装npm包 & 生成静态文件
      - name: Install and publish
        run: |
          npm install
          npm run build

      # 将静态文件部署到阿里云
      - name: Deploy to aliyun server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public"
          REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
          REMOTE_USER: "root"
          TARGET: "/code/hexo-blog"

      # 将静态文件部署到Vultr VPS
      - name: Deploy to Vultr VPS
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.NJ51_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public"
          REMOTE_HOST: ${{ secrets.NJ51_SERVER_HOST }}
          REMOTE_USER: "root"
          TARGET: "/code/kobin-blog" # 静态资源存放目录

      # 将静态文件部署到github pages
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: blog
          BRANCH: master
          FOLDER: public
